export enum Region {
  Tunis = 'Tunis',
  Ariana = 'Ariana',
  BenArous = 'Ben Arous',
  Manouba = 'Manouba',
  Nabeul = 'Nabeul',
  Zaghouan = 'Zaghouan',
  Bizerte = 'Bizerte',
  Beja = 'Beja',
  Jendouba = 'Jendouba',
  Kef = 'Kef',
  Siliana = 'Siliana',
  Sousse = 'Sousse',
  Monastir = 'Monastir',
  Mahdia = 'Mahdia',
  Kairouan = 'Kairouan',
  Kasserine = 'Kasserine',
  SidiBouzid = 'Sidi Bouzid',
  Sfax = 'Sfax',
  Gabes = 'Gabes',
  Medenine = 'Medenine',
  Tataouine = 'Tataouine',
  Gafsa = 'Gafsa',
  Tozeur = 'Tozeur',
  Kebili = 'Kebili'
}
